name: Sky Benefits
favicon: null
layout_spectrum: 0.92358
typography_spectrum: 0.6682306749280542
title: The Ultimate Solution
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#139ada'
    - '#444444'
    - '#e4e4e4'
    - '#b5b5b5'
    - '#838383'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
